QT    += core gui quick widgets quickwidgets qml charts datavisualization

TARGET = quickwidget
TEMPLATE = app


INCLUDEPATH += d:/opencv/build/include\
INCLUDEPATH += d:/opencv/build/include/opencv\
INCLUDEPATH += d:/opencv/build/include/opencv2\

LIBS += -Ld:/opencv/build/x64/vc12/staticlib \
    -l*
LIBS += -Ld:/opencv/build/x64/vc12/lib \
-lopencv_ts300 \
-lopencv_world300

#CONFIG(debug,debug|release) {
#LIBS += -Ld:/opencv/build/x64/vc12/staticlib \
#    -lopencv_highgui300d \
#    -lopencv_imgproc300d \
#    -lopencv_features2d300d \
#    -lopencv_calib3d300d \
#-lopencv_core300d \
#-lIlmImf \
#-lippicvmt \
#-llibjasper\
#-llibjasperd\
#-llibjpeg\
#-llibtiff\
#-lopencv_features2d300d\
#-lopencv_flann300d\
#-lopencv_hal300d
#}
#LIBS += -Ld:/opencv/build/x64/vc12/lib \
#-lopencv_ts300d \
#-lopencv_world300d

#LIBS += -Ld:/opencv/build/x64/vc12/bin \
#-lopencv_world300d
#} else {
#LIBS += -LLd:/opencv/build/x64/vc12/lib \
#    -lopencv_highgui300 \
#    -lopencv_imgproc300 \
#    -lopencv_features2d300 \
#    -lopencv_core300
#}

LIBS += "-LC:/Program Files/JAI/SDK/library/CPP/lib/Win64_x64" -lJai_Factory
INCLUDEPATH += "C:/Program Files/JAI/SDK/library/CPP/include/"
#"F:/Qt-project/include/"

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += main.cpp \
#    ../../../../../../../../../../root/menu/fileio.cpp \
#    ../../../../../../../../../../root/menu/fileio2.cpp \
#    ../../../../../../qt_project/Select_Area/drag.cpp \
#    ../../../../../../qt_project/Select_Area/fc.cpp \
#    /media/root/LENOVO/WpSystem/Qt5/Examples/Qt-5.10.0/quick/quickwidgets/quickwidget/dragchart.cpp \
    components/layouts/qtmaterialsnackbarlayout.cpp \
    components/lib/qtmaterialcheckable.cpp \
    components/lib/qtmaterialcheckable_internal.cpp \
    components/lib/qtmaterialoverlaywidget.cpp \
    components/lib/qtmaterialripple.cpp \
    components/lib/qtmaterialrippleoverlay.cpp \
    components/lib/qtmaterialstatetransition.cpp \
    components/lib/qtmaterialstyle.cpp \
    components/lib/qtmaterialtheme.cpp \
    components/qtmaterialappbar.cpp \
    components/qtmaterialautocomplete.cpp \
    components/qtmaterialautocomplete_internal.cpp \
    components/qtmaterialavatar.cpp \
    components/qtmaterialbadge.cpp \
    components/qtmaterialcheckbox.cpp \
    components/qtmaterialcircularprogress.cpp \
    components/qtmaterialcircularprogress_internal.cpp \
    components/qtmaterialdialog.cpp \
    components/qtmaterialdialog_internal.cpp \
    components/qtmaterialdrawer.cpp \
    components/qtmaterialdrawer_internal.cpp \
    components/qtmaterialfab.cpp \
    components/qtmaterialflatbutton.cpp \
    components/qtmaterialflatbutton_internal.cpp \
    components/qtmaterialiconbutton.cpp \
    components/qtmateriallist.cpp \
    components/qtmateriallistitem.cpp \
    components/qtmaterialmenu.cpp \
    components/qtmaterialmenu_internal.cpp \
    components/qtmaterialpaper.cpp \
    components/qtmaterialprogress.cpp \
    components/qtmaterialprogress_internal.cpp \
    components/qtmaterialradiobutton.cpp \
    components/qtmaterialraisedbutton.cpp \
    components/qtmaterialscrollbar.cpp \
    components/qtmaterialscrollbar_internal.cpp \
    components/qtmaterialslider.cpp \
    components/qtmaterialslider_internal.cpp \
    components/qtmaterialsnackbar.cpp \
    components/qtmaterialsnackbar_internal.cpp \
    components/qtmaterialtable.cpp \
    components/qtmaterialtabs.cpp \
    components/qtmaterialtabs_internal.cpp \
    components/qtmaterialtextfield.cpp \
    components/qtmaterialtextfield_internal.cpp \
    components/qtmaterialtoggle.cpp \
    components/qtmaterialtoggle_internal.cpp \
    uxforcew.cpp \
    ux3dw.cpp \
    uxcubic.cpp \
    uxyangw.cpp \
    uxtumbler.cpp \
    uxmenu.cpp \
    uxmenubutton.cpp \
    uxava.cpp \
    uxautop.cpp \
    uxmainwindow.cpp \
    uxzoomchartview.cpp \
    uxzoomchart.cpp \
    uxdatav.cpp \
    uxwidget.cpp \
    uxfile.cpp \
    uxdl.cpp \
    uxdlc.cpp \
    uxmbg.cpp \
    uxcb.cpp \
    uxlp.cpp \
    uxlptestw.cpp \
    uxcdraw.cpp \
    uxcdrawhelper.cpp \
    timehelper.cpp \
    uxccdread.cpp \
    uxccdper.cpp \
    uxccdw.cpp \
    F:/Qt-project/include/uxccddownb.cpp \
    F:/Qt-project/include/uxccdleftb.cpp \
    F:/Qt-project/include/uxccdrightb.cpp \
    F:/Qt-project/include/uxccdupb.cpp \
    uxpepiserver.cpp \
    uxpipeclient.cpp \
    uxservermessageemiter.cpp \
    uxdpainter.cpp \
    uxfilemapread.cpp \
    mainwindow.cpp \
    uxtest45.cpp \
    uxccdsimple.cpp \
    cver.cpp
HEADERS += \
#    /root/menu/fileio.h \
#    /root/menu/fileio2.h \
#    ../../../../../../qt_project/Select_Area/drag.h \
#    ../../../../../../qt_project/Select_Area/fc.h \
#    /media/root/LENOVO/WpSystem/Qt5/Examples/Qt-5.10.0/quick/quickwidgets/quickwidget/dragchart.h \
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCBase.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCError.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCException.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCLinkage.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCString.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCStringVector.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCSynch.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCTypes.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCUtilities.h "\
    "C:/Program Files/JAI/SDK/library/CPP/include/Base/GCVersion.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CLAllAdapter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ClAllSerial.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CLAutoBuffer.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CLException.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CLPort.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CLProtocol.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CLProtocolLinkage.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ClSerial.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ClSerialTypes.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/CVersion.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/DeviceID.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ISerial.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ISerialAdapter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ISerialAdapterCStyle.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/XMLID.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/Int64Lexer.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/Int64MathParser.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/Lexer.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/MathParser.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/MathParserDll.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/StrMap.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MathParser/SymTable.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/AutovectorImpl.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/BaseT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Boolean.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/BooleanT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Category.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Command.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/CommandT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Converter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/DcamAccessCtrlReg.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/DllManager.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/EnumEntry.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Enumeration.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/EnumerationT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Exception.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Float.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/FloatT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/FltReg.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/gcmemory.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/GenApiImpl.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/GenApiUtilities.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/GlobalPragmas.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/IEEE1212Parser.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/INodeMapPrivate.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/INodePrivate.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/IntConverter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Integer.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/IntegerT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/IntKey.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/IntReg.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/IntSwissKnife.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/MaskedIntReg.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Node.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/NodeMacros.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/NodeMap.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/NodeT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/PerfectHash.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/PointerImpl.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/PolyReference.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Port.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/PrivateTypes.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Register.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/RegisterT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/SelectorDigit.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/SmartFeature.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/StringNode.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/StringReg.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/StringsToIDs.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/StringT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/SwissKnife.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/SwissKnifeT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Txtkey.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/Value2String.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/ValueCache.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/ValueNode.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/impl/ValueT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Autovector.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Callback.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ChunkAdapter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ChunkAdapterDcam.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ChunkAdapterGeneric.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ChunkAdapterGEV.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ChunkAdapterU3V.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ChunkPort.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Compatibility.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Container.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Counter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/DLLLoad.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EnumClasses.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EventAdapter.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EventAdapter1394.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EventAdapterGeneric.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EventAdapterGEV.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EventAdapterU3V.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/EventPort.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Filestream.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/GenApi.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/GenApiDll.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/GenApiLinkage.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/GenApiVersion.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IBase.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IBoolean.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ICategory.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IChunkPort.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ICommand.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IDestroy.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IDeviceInfo.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IEnumEntry.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IEnumeration.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IEnumerationT.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IFloat.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IInteger.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/INode.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/INodeMap.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/INodeMapDyn.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IPort.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IPortConstruct.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IPortRecorder.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IRegister.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ISelector.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/ISelectorDigit.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IString.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/IValue.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Log.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/NodeCallback.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/NodeCallbackImpl.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/NodeMapRef.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/NodeMapUtils.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Persistence.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Pointer.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/PortImpl.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/PortWriteList.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Reference.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/RegisterPortImpl.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/RegisterSetHelper.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/SelectorSet.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/StructPort.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Synch.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenApi/Types.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Log/CLog.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Log/LogDll.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Extensions/Utilities.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/threading/BoostThreads.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/threading/DummyThreads.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/threading/MSThreads.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/threading/OmniThreads.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/threading/PThreads.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/threading/Threading.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/AbortAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Appender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/AppendersFactory.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/AppenderSkeleton.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/BasicConfigurator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/BasicLayout.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/BufferingAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Category.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/CategoryStream.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/config-openvms.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/config-win32.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/config.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Configurator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/convenience.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Export.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/FactoryParams.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/FileAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Filter.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/FixedContextCategory.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/HierarchyMaintainer.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/IdsaAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Layout.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/LayoutAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/LayoutsFactory.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/LevelEvaluator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/LoggingEvent.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Manipulator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/NDC.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/NTEventLogAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/OstreamAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/PassThroughLayout.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/PatternLayout.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Portability.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Priority.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/PropertyConfigurator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/RemoteSyslogAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/RollingFileAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/SimpleConfigurator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/SimpleLayout.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/StringQueueAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/SyslogAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/TimeStamp.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/TriggeringEventEvaluator.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/TriggeringEventEvaluatorFactory.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/log4cpp/Win32DebugAppender.hh"\
    "C:/Program Files/JAI/SDK/library/CPP/include/TLI/Client.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/TLI/Error.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/TLI/GenTL.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/TLI/Platform.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/TLI/System.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/_GenICamVersion.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/FactoryPlatform.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenICam.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/GenICamVersion.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/InheritEnum.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Jai_Error.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/jai_factory.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Jai_Factory_Dynamic.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Jai_Registry.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/Jai_Types.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/RegistryPlatform.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/tiff.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/tiffconf.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/tiffio.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/tiffvers.h"\
    "C:/Program Files/JAI/SDK/library/CPP/include/VLib.h" \
    components/layouts/qtmaterialsnackbarlayout.h \
    components/layouts/qtmaterialsnackbarlayout_p.h \
    components/lib/qtmaterialcheckable.h \
    components/lib/qtmaterialcheckable_internal.h \
    components/lib/qtmaterialcheckable_p.h \
    components/lib/qtmaterialoverlaywidget.h \
    components/lib/qtmaterialripple.h \
    components/lib/qtmaterialrippleoverlay.h \
    components/lib/qtmaterialstatetransition.h \
    components/lib/qtmaterialstatetransitionevent.h \
    components/lib/qtmaterialstyle.h \
    components/lib/qtmaterialstyle_p.h \
    components/lib/qtmaterialtheme.h \
    components/lib/qtmaterialtheme_p.h \
    components/qtmaterialappbar.h \
    components/qtmaterialappbar_p.h \
    components/qtmaterialautocomplete.h \
    components/qtmaterialautocomplete_internal.h \
    components/qtmaterialautocomplete_p.h \
    components/qtmaterialavatar.h \
    components/qtmaterialavatar_p.h \
    components/qtmaterialbadge.h \
    components/qtmaterialbadge_p.h \
    components/qtmaterialcheckbox.h \
    components/qtmaterialcheckbox_p.h \
    components/qtmaterialcircularprogress.h \
    components/qtmaterialcircularprogress_internal.h \
    components/qtmaterialcircularprogress_p.h \
    components/qtmaterialdialog.h \
    components/qtmaterialdialog_internal.h \
    components/qtmaterialdialog_p.h \
    components/qtmaterialdrawer.h \
    components/qtmaterialdrawer_internal.h \
    components/qtmaterialdrawer_p.h \
    components/qtmaterialfab.h \
    components/qtmaterialfab_p.h \
    components/qtmaterialflatbutton.h \
    components/qtmaterialflatbutton_internal.h \
    components/qtmaterialflatbutton_p.h \
    components/qtmaterialiconbutton.h \
    components/qtmaterialiconbutton_p.h \
    components/qtmateriallist.h \
    components/qtmateriallist_p.h \
    components/qtmateriallistitem.h \
    components/qtmateriallistitem_p.h \
    components/qtmaterialmenu.h \
    components/qtmaterialmenu_internal.h \
    components/qtmaterialmenu_p.h \
    components/qtmaterialpaper.h \
    components/qtmaterialpaper_p.h \
    components/qtmaterialprogress.h \
    components/qtmaterialprogress_internal.h \
    components/qtmaterialprogress_p.h \
    components/qtmaterialradiobutton.h \
    components/qtmaterialradiobutton_p.h \
    components/qtmaterialraisedbutton.h \
    components/qtmaterialraisedbutton_p.h \
    components/qtmaterialscrollbar.h \
    components/qtmaterialscrollbar_internal.h \
    components/qtmaterialscrollbar_p.h \
    components/qtmaterialslider.h \
    components/qtmaterialslider_internal.h \
    components/qtmaterialslider_p.h \
    components/qtmaterialsnackbar.h \
    components/qtmaterialsnackbar_internal.h \
    components/qtmaterialsnackbar_p.h \
    components/qtmaterialtable.h \
    components/qtmaterialtable_p.h \
    components/qtmaterialtabs.h \
    components/qtmaterialtabs_internal.h \
    components/qtmaterialtabs_p.h \
    components/qtmaterialtextfield.h \
    components/qtmaterialtextfield_internal.h \
    components/qtmaterialtextfield_p.h \
    components/qtmaterialtoggle.h \
    components/qtmaterialtoggle_internal.h \
    components/qtmaterialtoggle_p.h \
    uxforcew.h \
    ux3dw.h \
    uxcubic.h \
    uxyangw.h \
    uxtumbler.h \
    uxmenu.h \
    uxmenubutton.h \
    uxava.h \
    uxautop.h \
    uxmainwindow.h \
    uxzoomchartview.h \
    uxzoomchart.h \
    uxdatav.h \
    uxwidget.h \
    uxfile.h \
    uxdl.h \
    uxdlc.h \
    uxmbg.h \
    uxcb.h \
    uxcdraw.h \
    uxlp.h \
    uxlptestw.h \
    uxcdrawhelper.h \
    uxccdper.h \
    uxccdread.h \
    uxccdw.h \
    timehelper.h \
    F:/Qt-project/include/uxccddownb.h \
    F:/Qt-project/include/uxccdleftb.h \
    F:/Qt-project/include/uxccdrightb.h \
    F:/Qt-project/include/uxccdupb.h \
    uxpepiserver.h \
    uxpipeclient.h \
    uxservermessageemiter.h \
    uxdpainter.h \
    uxfilemapread.h \
    mainwindow.h \
    uxtest45.h \
    uxccdsimple.h \
    cver.h

RESOURCES += quickwidget.qrc

target.path = $$[QT_INSTALL_EXAMPLES]/quick/quickwidgets/quickwidget
INSTALLS += target

DISTFILES += \
    qtquickcontrols2.conf \
    fonts/Roboto/Roboto-Black.ttf \
    fonts/Roboto/Roboto-BlackItalic.ttf \
    fonts/Roboto/Roboto-Bold.ttf \
    fonts/Roboto/Roboto-BoldItalic.ttf \
    fonts/Roboto/Roboto-Italic.ttf \
    fonts/Roboto/Roboto-Light.ttf \
    fonts/Roboto/Roboto-LightItalic.ttf \
    fonts/Roboto/Roboto-Medium.ttf \
    fonts/Roboto/Roboto-MediumItalic.ttf \
    fonts/Roboto/Roboto-Regular.ttf \
    fonts/Roboto/Roboto-Thin.ttf \
    fonts/Roboto/Roboto-ThinItalic.ttf \
    gifs/appbar.gif \
    gifs/autocomplete.gif \
    gifs/avatar.gif \
    gifs/badge.gif \
    gifs/checkbox.gif \
    gifs/circularprogress.gif \
    gifs/dialog.gif \
    gifs/drawer.gif \
    gifs/fab.gif \
    gifs/flatbutton.gif \
    gifs/iconbutton.gif \
    gifs/progress.gif \
    gifs/radiobutton.gif \
    gifs/raisedbutton.gif \
    gifs/scrollbar.gif \
    gifs/slider.gif \
    gifs/snackbar.gif \
    gifs/tabs.gif \
    gifs/textfield.gif \
    gifs/toggle.gif \
    components/icons/action/svg/production/ic_3d_rotation_24px.svg \
    components/icons/action/svg/production/ic_accessibility_24px.svg \
    components/icons/action/svg/production/ic_accessible_24px.svg \
    components/icons/action/svg/production/ic_account_balance_24px.svg \
    components/icons/action/svg/production/ic_account_balance_wallet_24px.svg \
    components/icons/action/svg/production/ic_account_box_24px.svg \
    components/icons/action/svg/production/ic_account_circle_24px.svg \
    components/icons/action/svg/production/ic_add_shopping_cart_24px.svg \
    components/icons/action/svg/production/ic_alarm_24px.svg \
    components/icons/action/svg/production/ic_alarm_add_24px.svg \
    components/icons/action/svg/production/ic_alarm_off_24px.svg \
    components/icons/action/svg/production/ic_alarm_on_24px.svg \
    components/icons/action/svg/production/ic_all_out_24px.svg \
    components/icons/action/svg/production/ic_android_24px.svg \
    components/icons/action/svg/production/ic_announcement_24px.svg \
    components/icons/action/svg/production/ic_aspect_ratio_24px.svg \
    components/icons/action/svg/production/ic_assessment_24px.svg \
    components/icons/action/svg/production/ic_assignment_24px.svg \
    components/icons/action/svg/production/ic_assignment_ind_24px.svg \
    components/icons/action/svg/production/ic_assignment_late_24px.svg \
    components/icons/action/svg/production/ic_assignment_return_24px.svg \
    components/icons/action/svg/production/ic_assignment_returned_24px.svg \
    components/icons/action/svg/production/ic_assignment_turned_in_24px.svg \
    components/icons/action/svg/production/ic_autorenew_24px.svg \
    components/icons/action/svg/production/ic_backup_24px.svg \
    components/icons/action/svg/production/ic_book_24px.svg \
    components/icons/action/svg/production/ic_bookmark_24px.svg \
    components/icons/action/svg/production/ic_bookmark_border_24px.svg \
    components/icons/action/svg/production/ic_bug_report_24px.svg \
    components/icons/action/svg/production/ic_build_24px.svg \
    components/icons/action/svg/production/ic_cached_24px.svg \
    components/icons/action/svg/production/ic_camera_enhance_24px.svg \
    components/icons/action/svg/production/ic_card_giftcard_24px.svg \
    components/icons/action/svg/production/ic_card_membership_24px.svg \
    components/icons/action/svg/production/ic_card_travel_24px.svg \
    components/icons/action/svg/production/ic_change_history_24px.svg \
    components/icons/action/svg/production/ic_check_circle_24px.svg \
    components/icons/action/svg/production/ic_chrome_reader_mode_24px.svg \
    components/icons/action/svg/production/ic_class_24px.svg \
    components/icons/action/svg/production/ic_code_24px.svg \
    components/icons/action/svg/production/ic_compare_arrows_24px.svg \
    components/icons/action/svg/production/ic_copyright_24px.svg \
    components/icons/action/svg/production/ic_credit_card_24px.svg \
    components/icons/action/svg/production/ic_dashboard_24px.svg \
    components/icons/action/svg/production/ic_date_range_24px.svg \
    components/icons/action/svg/production/ic_delete_24px.svg \
    components/icons/action/svg/production/ic_delete_forever_24px.svg \
    components/icons/action/svg/production/ic_description_24px.svg \
    components/icons/action/svg/production/ic_dns_24px.svg \
    components/icons/action/svg/production/ic_done_24px.svg \
    components/icons/action/svg/production/ic_done_all_24px.svg \
    components/icons/action/svg/production/ic_donut_large_24px.svg \
    components/icons/action/svg/production/ic_donut_small_24px.svg \
    components/icons/action/svg/production/ic_eject_24px.svg \
    components/icons/action/svg/production/ic_euro_symbol_24px.svg \
    components/icons/action/svg/production/ic_event_24px.svg \
    components/icons/action/svg/production/ic_event_seat_24px.svg \
    components/icons/action/svg/production/ic_exit_to_app_24px.svg \
    components/icons/action/svg/production/ic_explore_24px.svg \
    components/icons/action/svg/production/ic_extension_24px.svg \
    components/icons/action/svg/production/ic_face_24px.svg \
    components/icons/action/svg/production/ic_favorite_24px.svg \
    components/icons/action/svg/production/ic_favorite_border_24px.svg \
    components/icons/action/svg/production/ic_feedback_24px.svg \
    components/icons/action/svg/production/ic_find_in_page_24px.svg \
    components/icons/action/svg/production/ic_find_replace_24px.svg \
    components/icons/action/svg/production/ic_fingerprint_24px.svg \
    components/icons/action/svg/production/ic_flight_land_24px.svg \
    components/icons/action/svg/production/ic_flight_takeoff_24px.svg \
    components/icons/action/svg/production/ic_flip_to_back_24px.svg \
    components/icons/action/svg/production/ic_flip_to_front_24px.svg \
    components/icons/action/svg/production/ic_g_translate_24px.svg \
    components/icons/action/svg/production/ic_gavel_24px.svg \
    components/icons/action/svg/production/ic_get_app_24px.svg \
    components/icons/action/svg/production/ic_gif_24px.svg \
    components/icons/action/svg/production/ic_grade_24px.svg \
    components/icons/action/svg/production/ic_group_work_24px.svg \
    components/icons/action/svg/production/ic_help_24px.svg \
    components/icons/action/svg/production/ic_help_outline_24px.svg \
    components/icons/action/svg/production/ic_highlight_off_24px.svg \
    components/icons/action/svg/production/ic_history_24px.svg \
    components/icons/action/svg/production/ic_home_24px.svg \
    components/icons/action/svg/production/ic_hourglass_empty_24px.svg \
    components/icons/action/svg/production/ic_hourglass_full_24px.svg \
    components/icons/action/svg/production/ic_http_24px.svg \
    components/icons/action/svg/production/ic_https_24px.svg \
    components/icons/action/svg/production/ic_important_devices_24px.svg \
    components/icons/action/svg/production/ic_info_24px.svg \
    components/icons/action/svg/production/ic_info_outline_24px.svg \
    components/icons/action/svg/production/ic_input_24px.svg \
    components/icons/action/svg/production/ic_invert_colors_24px.svg \
    components/icons/action/svg/production/ic_label_24px.svg \
    components/icons/action/svg/production/ic_label_outline_24px.svg \
    components/icons/action/svg/production/ic_language_24px.svg \
    components/icons/action/svg/production/ic_launch_24px.svg \
    components/icons/action/svg/production/ic_lightbulb_outline_24px.svg \
    components/icons/action/svg/production/ic_line_style_24px.svg \
    components/icons/action/svg/production/ic_line_weight_24px.svg \
    components/icons/action/svg/production/ic_list_24px.svg \
    components/icons/action/svg/production/ic_lock_24px.svg \
    components/icons/action/svg/production/ic_lock_open_24px.svg \
    components/icons/action/svg/production/ic_lock_outline_24px.svg \
    components/icons/action/svg/production/ic_loyalty_24px.svg \
    components/icons/action/svg/production/ic_markunread_mailbox_24px.svg \
    components/icons/action/svg/production/ic_motorcycle_24px.svg \
    components/icons/action/svg/production/ic_note_add_24px.svg \
    components/icons/action/svg/production/ic_offline_pin_24px.svg \
    components/icons/action/svg/production/ic_opacity_24px.svg \
    components/icons/action/svg/production/ic_open_in_browser_24px.svg \
    components/icons/action/svg/production/ic_open_in_new_24px.svg \
    components/icons/action/svg/production/ic_open_with_24px.svg \
    components/icons/action/svg/production/ic_pageview_24px.svg \
    components/icons/action/svg/production/ic_pan_tool_24px.svg \
    components/icons/action/svg/production/ic_payment_24px.svg \
    components/icons/action/svg/production/ic_perm_camera_mic_24px.svg \
    components/icons/action/svg/production/ic_perm_contact_calendar_24px.svg \
    components/icons/action/svg/production/ic_perm_data_setting_24px.svg \
    components/icons/action/svg/production/ic_perm_device_information_24px.svg \
    components/icons/action/svg/production/ic_perm_identity_24px.svg \
    components/icons/action/svg/production/ic_perm_media_24px.svg \
    components/icons/action/svg/production/ic_perm_phone_msg_24px.svg \
    components/icons/action/svg/production/ic_perm_scan_wifi_24px.svg \
    components/icons/action/svg/production/ic_pets_24px.svg \
    components/icons/action/svg/production/ic_picture_in_picture_24px.svg \
    components/icons/action/svg/production/ic_picture_in_picture_alt_24px.svg \
    components/icons/action/svg/production/ic_play_for_work_24px.svg \
    components/icons/action/svg/production/ic_polymer_24px.svg \
    components/icons/action/svg/production/ic_power_settings_new_24px.svg \
    components/icons/action/svg/production/ic_pregnant_woman_24px.svg \
    components/icons/action/svg/production/ic_print_24px.svg \
    components/icons/action/svg/production/ic_query_builder_24px.svg \
    components/icons/action/svg/production/ic_question_answer_24px.svg \
    components/icons/action/svg/production/ic_receipt_24px.svg \
    components/icons/action/svg/production/ic_record_voice_over_24px.svg \
    components/icons/action/svg/production/ic_redeem_24px.svg \
    components/icons/action/svg/production/ic_remove_shopping_cart_24px.svg \
    components/icons/action/svg/production/ic_reorder_24px.svg \
    components/icons/action/svg/production/ic_report_problem_24px.svg \
    components/icons/action/svg/production/ic_restore_24px.svg \
    components/icons/action/svg/production/ic_restore_page_24px.svg \
    components/icons/action/svg/production/ic_room_24px.svg \
    components/icons/action/svg/production/ic_rounded_corner_24px.svg \
    components/icons/action/svg/production/ic_rowing_24px.svg \
    components/icons/action/svg/production/ic_schedule_24px.svg \
    components/icons/action/svg/production/ic_search_24px.svg \
    components/icons/action/svg/production/ic_settings_24px.svg \
    components/icons/action/svg/production/ic_settings_applications_24px.svg \
    components/icons/action/svg/production/ic_settings_backup_restore_24px.svg \
    components/icons/action/svg/production/ic_settings_bluetooth_24px.svg \
    components/icons/action/svg/production/ic_settings_brightness_24px.svg \
    components/icons/action/svg/production/ic_settings_cell_24px.svg \
    components/icons/action/svg/production/ic_settings_ethernet_24px.svg \
    components/icons/action/svg/production/ic_settings_input_antenna_24px.svg \
    components/icons/action/svg/production/ic_settings_input_component_24px.svg \
    components/icons/action/svg/production/ic_settings_input_composite_24px.svg \
    components/icons/action/svg/production/ic_settings_input_hdmi_24px.svg \
    components/icons/action/svg/production/ic_settings_input_svideo_24px.svg \
    components/icons/action/svg/production/ic_settings_overscan_24px.svg \
    components/icons/action/svg/production/ic_settings_phone_24px.svg \
    components/icons/action/svg/production/ic_settings_power_24px.svg \
    components/icons/action/svg/production/ic_settings_remote_24px.svg \
    components/icons/action/svg/production/ic_settings_voice_24px.svg \
    components/icons/action/svg/production/ic_shop_24px.svg \
    components/icons/action/svg/production/ic_shop_two_24px.svg \
    components/icons/action/svg/production/ic_shopping_basket_24px.svg \
    components/icons/action/svg/production/ic_shopping_cart_24px.svg \
    components/icons/action/svg/production/ic_speaker_notes_24px.svg \
    components/icons/action/svg/production/ic_speaker_notes_off_24px.svg \
    components/icons/action/svg/production/ic_spellcheck_24px.svg \
    components/icons/action/svg/production/ic_stars_24px.svg \
    components/icons/action/svg/production/ic_store_24px.svg \
    components/icons/action/svg/production/ic_subject_24px.svg \
    components/icons/action/svg/production/ic_supervisor_account_24px.svg \
    components/icons/action/svg/production/ic_swap_horiz_24px.svg \
    components/icons/action/svg/production/ic_swap_vert_24px.svg \
    components/icons/action/svg/production/ic_swap_vertical_circle_24px.svg \
    components/icons/action/svg/production/ic_system_update_alt_24px.svg \
    components/icons/action/svg/production/ic_tab_24px.svg \
    components/icons/action/svg/production/ic_tab_unselected_24px.svg \
    components/icons/action/svg/production/ic_theaters_24px.svg \
    components/icons/action/svg/production/ic_thumb_down_24px.svg \
    components/icons/action/svg/production/ic_thumb_up_24px.svg \
    components/icons/action/svg/production/ic_thumbs_up_down_24px.svg \
    components/icons/action/svg/production/ic_timeline_24px.svg \
    components/icons/action/svg/production/ic_toc_24px.svg \
    components/icons/action/svg/production/ic_today_24px.svg \
    components/icons/action/svg/production/ic_toll_24px.svg \
    components/icons/action/svg/production/ic_touch_app_24px.svg \
    components/icons/action/svg/production/ic_track_changes_24px.svg \
    components/icons/action/svg/production/ic_translate_24px.svg \
    components/icons/action/svg/production/ic_trending_down_24px.svg \
    components/icons/action/svg/production/ic_trending_flat_24px.svg \
    components/icons/action/svg/production/ic_trending_up_24px.svg \
    components/icons/action/svg/production/ic_turned_in_24px.svg \
    components/icons/action/svg/production/ic_turned_in_not_24px.svg \
    components/icons/action/svg/production/ic_update_24px.svg \
    components/icons/action/svg/production/ic_verified_user_24px.svg \
    components/icons/action/svg/production/ic_view_agenda_24px.svg \
    components/icons/action/svg/production/ic_view_array_24px.svg \
    components/icons/action/svg/production/ic_view_carousel_24px.svg \
    components/icons/action/svg/production/ic_view_column_24px.svg \
    components/icons/action/svg/production/ic_view_day_24px.svg \
    components/icons/action/svg/production/ic_view_headline_24px.svg \
    components/icons/action/svg/production/ic_view_list_24px.svg \
    components/icons/action/svg/production/ic_view_module_24px.svg \
    components/icons/action/svg/production/ic_view_quilt_24px.svg \
    components/icons/action/svg/production/ic_view_stream_24px.svg \
    components/icons/action/svg/production/ic_view_week_24px.svg \
    components/icons/action/svg/production/ic_visibility_24px.svg \
    components/icons/action/svg/production/ic_visibility_off_24px.svg \
    components/icons/action/svg/production/ic_watch_later_24px.svg \
    components/icons/action/svg/production/ic_work_24px.svg \
    components/icons/action/svg/production/ic_youtube_searched_for_24px.svg \
    components/icons/action/svg/production/ic_zoom_in_24px.svg \
    components/icons/action/svg/production/ic_zoom_out_24px.svg \
    components/icons/alert/svg/production/ic_add_alert_24px.svg \
    components/icons/alert/svg/production/ic_error_24px.svg \
    components/icons/alert/svg/production/ic_error_outline_24px.svg \
    components/icons/alert/svg/production/ic_warning_24px.svg \
    components/icons/av/svg/production/ic_add_to_queue_24px.svg \
    components/icons/av/svg/production/ic_airplay_24px.svg \
    components/icons/av/svg/production/ic_album_24px.svg \
    components/icons/av/svg/production/ic_art_track_24px.svg \
    components/icons/av/svg/production/ic_av_timer_24px.svg \
    components/icons/av/svg/production/ic_branding_watermark_24px.svg \
    components/icons/av/svg/production/ic_call_to_action_24px.svg \
    components/icons/av/svg/production/ic_closed_caption_24px.svg \
    components/icons/av/svg/production/ic_equalizer_24px.svg \
    components/icons/av/svg/production/ic_explicit_24px.svg \
    components/icons/av/svg/production/ic_fast_forward_24px.svg \
    components/icons/av/svg/production/ic_fast_rewind_24px.svg \
    components/icons/av/svg/production/ic_featured_play_list_24px.svg \
    components/icons/av/svg/production/ic_featured_video_24px.svg \
    components/icons/av/svg/production/ic_fiber_dvr_24px.svg \
    components/icons/av/svg/production/ic_fiber_manual_record_24px.svg \
    components/icons/av/svg/production/ic_fiber_new_24px.svg \
    components/icons/av/svg/production/ic_fiber_pin_24px.svg \
    components/icons/av/svg/production/ic_fiber_smart_record_24px.svg \
    components/icons/av/svg/production/ic_forward_10_24px.svg \
    components/icons/av/svg/production/ic_forward_30_24px.svg \
    components/icons/av/svg/production/ic_forward_5_24px.svg \
    components/icons/av/svg/production/ic_games_24px.svg \
    components/icons/av/svg/production/ic_hd_24px.svg \
    components/icons/av/svg/production/ic_hearing_24px.svg \
    components/icons/av/svg/production/ic_high_quality_24px.svg \
    components/icons/av/svg/production/ic_library_add_24px.svg \
    components/icons/av/svg/production/ic_library_books_24px.svg \
    components/icons/av/svg/production/ic_library_music_24px.svg \
    components/icons/av/svg/production/ic_loop_24px.svg \
    components/icons/av/svg/production/ic_mic_24px.svg \
    components/icons/av/svg/production/ic_mic_none_24px.svg \
    components/icons/av/svg/production/ic_mic_off_24px.svg \
    components/icons/av/svg/production/ic_movie_24px.svg \
    components/icons/av/svg/production/ic_music_video_24px.svg \
    components/icons/av/svg/production/ic_new_releases_24px.svg \
    components/icons/av/svg/production/ic_not_interested_24px.svg \
    components/icons/av/svg/production/ic_note_24px.svg \
    components/icons/av/svg/production/ic_pause_24px.svg \
    components/icons/av/svg/production/ic_pause_circle_filled_24px.svg \
    components/icons/av/svg/production/ic_pause_circle_outline_24px.svg \
    components/icons/av/svg/production/ic_play_arrow_24px.svg \
    components/icons/av/svg/production/ic_play_circle_filled_24px.svg \
    components/icons/av/svg/production/ic_play_circle_outline_24px.svg \
    components/icons/av/svg/production/ic_playlist_add_24px.svg \
    components/icons/av/svg/production/ic_playlist_add_check_24px.svg \
    components/icons/av/svg/production/ic_playlist_play_24px.svg \
    components/icons/av/svg/production/ic_queue_24px.svg \
    components/icons/av/svg/production/ic_queue_music_24px.svg \
    components/icons/av/svg/production/ic_queue_play_next_24px.svg \
    components/icons/av/svg/production/ic_radio_24px.svg \
    components/icons/av/svg/production/ic_recent_actors_24px.svg \
    components/icons/av/svg/production/ic_remove_from_queue_24px.svg \
    components/icons/av/svg/production/ic_repeat_24px.svg \
    components/icons/av/svg/production/ic_repeat_one_24px.svg \
    components/icons/av/svg/production/ic_replay_10_24px.svg \
    components/icons/av/svg/production/ic_replay_24px.svg \
    components/icons/av/svg/production/ic_replay_30_24px.svg \
    components/icons/av/svg/production/ic_replay_5_24px.svg \
    components/icons/av/svg/production/ic_shuffle_24px.svg \
    components/icons/av/svg/production/ic_skip_next_24px.svg \
    components/icons/av/svg/production/ic_skip_previous_24px.svg \
    components/icons/av/svg/production/ic_slow_motion_video_24px.svg \
    components/icons/av/svg/production/ic_snooze_24px.svg \
    components/icons/av/svg/production/ic_sort_by_alpha_24px.svg \
    components/icons/av/svg/production/ic_stop_24px.svg \
    components/icons/av/svg/production/ic_subscriptions_24px.svg \
    components/icons/av/svg/production/ic_subtitles_24px.svg \
    components/icons/av/svg/production/ic_surround_sound_24px.svg \
    components/icons/av/svg/production/ic_video_call_24px.svg \
    components/icons/av/svg/production/ic_video_label_24px.svg \
    components/icons/av/svg/production/ic_video_library_24px.svg \
    components/icons/av/svg/production/ic_videocam_24px.svg \
    components/icons/av/svg/production/ic_videocam_off_24px.svg \
    components/icons/av/svg/production/ic_volume_down_24px.svg \
    components/icons/av/svg/production/ic_volume_mute_24px.svg \
    components/icons/av/svg/production/ic_volume_off_24px.svg \
    components/icons/av/svg/production/ic_volume_up_24px.svg \
    components/icons/av/svg/production/ic_web_24px.svg \
    components/icons/av/svg/production/ic_web_asset_24px.svg \
    components/icons/communication/svg/production/ic_business_24px.svg \
    components/icons/communication/svg/production/ic_call_24px.svg \
    components/icons/communication/svg/production/ic_call_end_24px.svg \
    components/icons/communication/svg/production/ic_call_made_24px.svg \
    components/icons/communication/svg/production/ic_call_merge_24px.svg \
    components/icons/communication/svg/production/ic_call_missed_24px.svg \
    components/icons/communication/svg/production/ic_call_missed_outgoing_24px.svg \
    components/icons/communication/svg/production/ic_call_received_24px.svg \
    components/icons/communication/svg/production/ic_call_split_24px.svg \
    components/icons/communication/svg/production/ic_chat_24px.svg \
    components/icons/communication/svg/production/ic_chat_bubble_24px.svg \
    components/icons/communication/svg/production/ic_chat_bubble_outline_24px.svg \
    components/icons/communication/svg/production/ic_clear_all_24px.svg \
    components/icons/communication/svg/production/ic_comment_24px.svg \
    components/icons/communication/svg/production/ic_contact_mail_24px.svg \
    components/icons/communication/svg/production/ic_contact_phone_24px.svg \
    components/icons/communication/svg/production/ic_contacts_24px.svg \
    components/icons/communication/svg/production/ic_dialer_sip_24px.svg \
    components/icons/communication/svg/production/ic_dialpad_24px.svg \
    components/icons/communication/svg/production/ic_email_24px.svg \
    components/icons/communication/svg/production/ic_forum_24px.svg \
    components/icons/communication/svg/production/ic_import_contacts_24px.svg \
    components/icons/communication/svg/production/ic_import_export_24px.svg \
    components/icons/communication/svg/production/ic_invert_colors_off_24px.svg \
    components/icons/communication/svg/production/ic_live_help_24px.svg \
    components/icons/communication/svg/production/ic_location_off_24px.svg \
    components/icons/communication/svg/production/ic_location_on_24px.svg \
    components/icons/communication/svg/production/ic_mail_outline_24px.svg \
    components/icons/communication/svg/production/ic_message_24px.svg \
    components/icons/communication/svg/production/ic_no_sim_24px.svg \
    components/icons/communication/svg/production/ic_phone_24px.svg \
    components/icons/communication/svg/production/ic_phonelink_erase_24px.svg \
    components/icons/communication/svg/production/ic_phonelink_lock_24px.svg \
    components/icons/communication/svg/production/ic_phonelink_ring_24px.svg \
    components/icons/communication/svg/production/ic_phonelink_setup_24px.svg \
    components/icons/communication/svg/production/ic_portable_wifi_off_24px.svg \
    components/icons/communication/svg/production/ic_present_to_all_24px.svg \
    components/icons/communication/svg/production/ic_ring_volume_24px.svg \
    components/icons/communication/svg/production/ic_rss_feed_24px.svg \
    components/icons/communication/svg/production/ic_screen_share_24px.svg \
    components/icons/communication/svg/production/ic_speaker_phone_24px.svg \
    components/icons/communication/svg/production/ic_stay_current_landscape_24px.svg \
    components/icons/communication/svg/production/ic_stay_current_portrait_24px.svg \
    components/icons/communication/svg/production/ic_stay_primary_landscape_24px.svg \
    components/icons/communication/svg/production/ic_stay_primary_portrait_24px.svg \
    components/icons/communication/svg/production/ic_stop_screen_share_24px.svg \
    components/icons/communication/svg/production/ic_swap_calls_24px.svg \
    components/icons/communication/svg/production/ic_textsms_24px.svg \
    components/icons/communication/svg/production/ic_voicemail_24px.svg \
    components/icons/communication/svg/production/ic_vpn_key_24px.svg \
    components/icons/content/svg/production/ic_add_24px.svg \
    components/icons/content/svg/production/ic_add_box_24px.svg \
    components/icons/content/svg/production/ic_add_circle_24px.svg \
    components/icons/content/svg/production/ic_add_circle_outline_24px.svg \
    components/icons/content/svg/production/ic_archive_24px.svg \
    components/icons/content/svg/production/ic_backspace_24px.svg \
    components/icons/content/svg/production/ic_block_24px.svg \
    components/icons/content/svg/production/ic_clear_24px.svg \
    components/icons/content/svg/production/ic_content_copy_24px.svg \
    components/icons/content/svg/production/ic_content_cut_24px.svg \
    components/icons/content/svg/production/ic_content_paste_24px.svg \
    components/icons/content/svg/production/ic_create_24px.svg \
    components/icons/content/svg/production/ic_delete_sweep_24px.svg \
    components/icons/content/svg/production/ic_drafts_24px.svg \
    components/icons/content/svg/production/ic_filter_list_24px.svg \
    components/icons/content/svg/production/ic_flag_24px.svg \
    components/icons/content/svg/production/ic_font_download_24px.svg \
    components/icons/content/svg/production/ic_forward_24px.svg \
    components/icons/content/svg/production/ic_gesture_24px.svg \
    components/icons/content/svg/production/ic_inbox_24px.svg \
    components/icons/content/svg/production/ic_link_24px.svg \
    components/icons/content/svg/production/ic_low_priority_24px.svg \
    components/icons/content/svg/production/ic_mail_24px.svg \
    components/icons/content/svg/production/ic_markunread_24px.svg \
    components/icons/content/svg/production/ic_move_to_inbox_24px.svg \
    components/icons/content/svg/production/ic_next_week_24px.svg \
    components/icons/content/svg/production/ic_redo_24px.svg \
    components/icons/content/svg/production/ic_remove_24px.svg \
    components/icons/content/svg/production/ic_remove_circle_24px.svg \
    components/icons/content/svg/production/ic_remove_circle_outline_24px.svg \
    components/icons/content/svg/production/ic_reply_24px.svg \
    components/icons/content/svg/production/ic_reply_all_24px.svg \
    components/icons/content/svg/production/ic_report_24px.svg \
    components/icons/content/svg/production/ic_save_24px.svg \
    components/icons/content/svg/production/ic_select_all_24px.svg \
    components/icons/content/svg/production/ic_send_24px.svg \
    components/icons/content/svg/production/ic_sort_24px.svg \
    components/icons/content/svg/production/ic_text_format_24px.svg \
    components/icons/content/svg/production/ic_unarchive_24px.svg \
    components/icons/content/svg/production/ic_undo_24px.svg \
    components/icons/content/svg/production/ic_weekend_24px.svg \
    components/icons/device/svg/production/ic_access_alarm_24px.svg \
    components/icons/device/svg/production/ic_access_alarms_24px.svg \
    components/icons/device/svg/production/ic_access_time_24px.svg \
    components/icons/device/svg/production/ic_add_alarm_24px.svg \
    components/icons/device/svg/production/ic_airplanemode_active_24px.svg \
    components/icons/device/svg/production/ic_airplanemode_inactive_24px.svg \
    components/icons/device/svg/production/ic_battery_20_24px.svg \
    components/icons/device/svg/production/ic_battery_30_24px.svg \
    components/icons/device/svg/production/ic_battery_50_24px.svg \
    components/icons/device/svg/production/ic_battery_60_24px.svg \
    components/icons/device/svg/production/ic_battery_80_24px.svg \
    components/icons/device/svg/production/ic_battery_90_24px.svg \
    components/icons/device/svg/production/ic_battery_alert_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_20_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_30_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_50_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_60_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_80_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_90_24px.svg \
    components/icons/device/svg/production/ic_battery_charging_full_24px.svg \
    components/icons/device/svg/production/ic_battery_full_24px.svg \
    components/icons/device/svg/production/ic_battery_std_24px.svg \
    components/icons/device/svg/production/ic_battery_unknown_24px.svg \
    components/icons/device/svg/production/ic_bluetooth_24px.svg \
    components/icons/device/svg/production/ic_bluetooth_connected_24px.svg \
    components/icons/device/svg/production/ic_bluetooth_disabled_24px.svg \
    components/icons/device/svg/production/ic_bluetooth_searching_24px.svg \
    components/icons/device/svg/production/ic_brightness_auto_24px.svg \
    components/icons/device/svg/production/ic_brightness_high_24px.svg \
    components/icons/device/svg/production/ic_brightness_low_24px.svg \
    components/icons/device/svg/production/ic_brightness_medium_24px.svg \
    components/icons/device/svg/production/ic_data_usage_24px.svg \
    components/icons/device/svg/production/ic_developer_mode_24px.svg \
    components/icons/device/svg/production/ic_devices_24px.svg \
    components/icons/device/svg/production/ic_dvr_24px.svg \
    components/icons/device/svg/production/ic_gps_fixed_24px.svg \
    components/icons/device/svg/production/ic_gps_not_fixed_24px.svg \
    components/icons/device/svg/production/ic_gps_off_24px.svg \
    components/icons/device/svg/production/ic_graphic_eq_24px.svg \
    components/icons/device/svg/production/ic_location_disabled_24px.svg \
    components/icons/device/svg/production/ic_location_searching_24px.svg \
    components/icons/device/svg/production/ic_network_cell_24px.svg \
    components/icons/device/svg/production/ic_network_wifi_24px.svg \
    components/icons/device/svg/production/ic_nfc_24px.svg \
    components/icons/device/svg/production/ic_screen_lock_landscape_24px.svg \
    components/icons/device/svg/production/ic_screen_lock_portrait_24px.svg \
    components/icons/device/svg/production/ic_screen_lock_rotation_24px.svg \
    components/icons/device/svg/production/ic_screen_rotation_24px.svg \
    components/icons/device/svg/production/ic_sd_storage_24px.svg \
    components/icons/device/svg/production/ic_settings_system_daydream_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_0_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_1_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_2_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_3_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_4_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_connected_no_internet_0_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_connected_no_internet_1_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_connected_no_internet_2_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_connected_no_internet_3_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_connected_no_internet_4_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_no_sim_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_null_24px.svg \
    components/icons/device/svg/production/ic_signal_cellular_off_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_0_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_1_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_1_bar_lock_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_2_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_2_bar_lock_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_3_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_3_bar_lock_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_4_bar_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_4_bar_lock_24px.svg \
    components/icons/device/svg/production/ic_signal_wifi_off_24px.svg \
    components/icons/device/svg/production/ic_storage_24px.svg \
    components/icons/device/svg/production/ic_usb_24px.svg \
    components/icons/device/svg/production/ic_wallpaper_24px.svg \
    components/icons/device/svg/production/ic_widgets_24px.svg \
    components/icons/device/svg/production/ic_wifi_lock_24px.svg \
    components/icons/device/svg/production/ic_wifi_tethering_24px.svg \
    components/icons/editor/svg/production/ic_attach_file_24px.svg \
    components/icons/editor/svg/production/ic_attach_money_24px.svg \
    components/icons/editor/svg/production/ic_border_all_24px.svg \
    components/icons/editor/svg/production/ic_border_bottom_24px.svg \
    components/icons/editor/svg/production/ic_border_clear_24px.svg \
    components/icons/editor/svg/production/ic_border_color_24px.svg \
    components/icons/editor/svg/production/ic_border_horizontal_24px.svg \
    components/icons/editor/svg/production/ic_border_inner_24px.svg \
    components/icons/editor/svg/production/ic_border_left_24px.svg \
    components/icons/editor/svg/production/ic_border_outer_24px.svg \
    components/icons/editor/svg/production/ic_border_right_24px.svg \
    components/icons/editor/svg/production/ic_border_style_24px.svg \
    components/icons/editor/svg/production/ic_border_top_24px.svg \
    components/icons/editor/svg/production/ic_border_vertical_24px.svg \
    components/icons/editor/svg/production/ic_bubble_chart_24px.svg \
    components/icons/editor/svg/production/ic_drag_handle_24px.svg \
    components/icons/editor/svg/production/ic_format_align_center_24px.svg \
    components/icons/editor/svg/production/ic_format_align_justify_24px.svg \
    components/icons/editor/svg/production/ic_format_align_left_24px.svg \
    components/icons/editor/svg/production/ic_format_align_right_24px.svg \
    components/icons/editor/svg/production/ic_format_bold_24px.svg \
    components/icons/editor/svg/production/ic_format_clear_24px.svg \
    components/icons/editor/svg/production/ic_format_color_fill_24px.svg \
    components/icons/editor/svg/production/ic_format_color_reset_24px.svg \
    components/icons/editor/svg/production/ic_format_color_text_24px.svg \
    components/icons/editor/svg/production/ic_format_indent_decrease_24px.svg \
    components/icons/editor/svg/production/ic_format_indent_increase_24px.svg \
    components/icons/editor/svg/production/ic_format_italic_24px.svg \
    components/icons/editor/svg/production/ic_format_line_spacing_24px.svg \
    components/icons/editor/svg/production/ic_format_list_bulleted_24px.svg \
    components/icons/editor/svg/production/ic_format_list_numbered_24px.svg \
    components/icons/editor/svg/production/ic_format_paint_24px.svg \
    components/icons/editor/svg/production/ic_format_quote_24px.svg \
    components/icons/editor/svg/production/ic_format_shapes_24px.svg \
    components/icons/editor/svg/production/ic_format_size_24px.svg \
    components/icons/editor/svg/production/ic_format_strikethrough_24px.svg \
    components/icons/editor/svg/production/ic_format_textdirection_l_to_r_24px.svg \
    components/icons/editor/svg/production/ic_format_textdirection_r_to_l_24px.svg \
    components/icons/editor/svg/production/ic_format_underlined_24px.svg \
    components/icons/editor/svg/production/ic_functions_24px.svg \
    components/icons/editor/svg/production/ic_highlight_24px.svg \
    components/icons/editor/svg/production/ic_insert_chart_24px.svg \
    components/icons/editor/svg/production/ic_insert_comment_24px.svg \
    components/icons/editor/svg/production/ic_insert_drive_file_24px.svg \
    components/icons/editor/svg/production/ic_insert_emoticon_24px.svg \
    components/icons/editor/svg/production/ic_insert_invitation_24px.svg \
    components/icons/editor/svg/production/ic_insert_link_24px.svg \
    components/icons/editor/svg/production/ic_insert_photo_24px.svg \
    components/icons/editor/svg/production/ic_linear_scale_24px.svg \
    components/icons/editor/svg/production/ic_merge_type_24px.svg \
    components/icons/editor/svg/production/ic_mode_comment_24px.svg \
    components/icons/editor/svg/production/ic_mode_edit_24px.svg \
    components/icons/editor/svg/production/ic_monetization_on_24px.svg \
    components/icons/editor/svg/production/ic_money_off_24px.svg \
    components/icons/editor/svg/production/ic_multiline_chart_24px.svg \
    components/icons/editor/svg/production/ic_pie_chart_24px.svg \
    components/icons/editor/svg/production/ic_pie_chart_outlined_24px.svg \
    components/icons/editor/svg/production/ic_publish_24px.svg \
    components/icons/editor/svg/production/ic_short_text_24px.svg \
    components/icons/editor/svg/production/ic_show_chart_24px.svg \
    components/icons/editor/svg/production/ic_space_bar_24px.svg \
    components/icons/editor/svg/production/ic_strikethrough_s_24px.svg \
    components/icons/editor/svg/production/ic_text_fields_24px.svg \
    components/icons/editor/svg/production/ic_title_24px.svg \
    components/icons/editor/svg/production/ic_vertical_align_bottom_24px.svg \
    components/icons/editor/svg/production/ic_vertical_align_center_24px.svg \
    components/icons/editor/svg/production/ic_vertical_align_top_24px.svg \
    components/icons/editor/svg/production/ic_wrap_text_24px.svg \
    components/icons/file/svg/production/ic_attachment_24px.svg \
    components/icons/file/svg/production/ic_cloud_24px.svg \
    components/icons/file/svg/production/ic_cloud_circle_24px.svg \
    components/icons/file/svg/production/ic_cloud_done_24px.svg \
    components/icons/file/svg/production/ic_cloud_download_24px.svg \
    components/icons/file/svg/production/ic_cloud_off_24px.svg \
    components/icons/file/svg/production/ic_cloud_queue_24px.svg \
    components/icons/file/svg/production/ic_cloud_upload_24px.svg \
    components/icons/file/svg/production/ic_create_new_folder_24px.svg \
    components/icons/file/svg/production/ic_file_download_24px.svg \
    components/icons/file/svg/production/ic_file_upload_24px.svg \
    components/icons/file/svg/production/ic_folder_24px.svg \
    components/icons/file/svg/production/ic_folder_open_24px.svg \
    components/icons/file/svg/production/ic_folder_shared_24px.svg \
    components/icons/hardware/svg/production/ic_cast_24px.svg \
    components/icons/hardware/svg/production/ic_cast_connected_24px.svg \
    components/icons/hardware/svg/production/ic_computer_24px.svg \
    components/icons/hardware/svg/production/ic_desktop_mac_24px.svg \
    components/icons/hardware/svg/production/ic_desktop_windows_24px.svg \
    components/icons/hardware/svg/production/ic_developer_board_24px.svg \
    components/icons/hardware/svg/production/ic_device_hub_24px.svg \
    components/icons/hardware/svg/production/ic_devices_other_24px.svg \
    components/icons/hardware/svg/production/ic_dock_24px.svg \
    components/icons/hardware/svg/production/ic_gamepad_24px.svg \
    components/icons/hardware/svg/production/ic_headset_24px.svg \
    components/icons/hardware/svg/production/ic_headset_mic_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_arrow_down_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_arrow_left_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_arrow_right_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_arrow_up_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_backspace_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_capslock_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_hide_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_return_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_tab_24px.svg \
    components/icons/hardware/svg/production/ic_keyboard_voice_24px.svg \
    components/icons/hardware/svg/production/ic_laptop_24px.svg \
    components/icons/hardware/svg/production/ic_laptop_chromebook_24px.svg \
    components/icons/hardware/svg/production/ic_laptop_mac_24px.svg \
    components/icons/hardware/svg/production/ic_laptop_windows_24px.svg \
    components/icons/hardware/svg/production/ic_memory_24px.svg \
    components/icons/hardware/svg/production/ic_mouse_24px.svg \
    components/icons/hardware/svg/production/ic_phone_android_24px.svg \
    components/icons/hardware/svg/production/ic_phone_iphone_24px.svg \
    components/icons/hardware/svg/production/ic_phonelink_24px.svg \
    components/icons/hardware/svg/production/ic_phonelink_off_24px.svg \
    components/icons/hardware/svg/production/ic_power_input_24px.svg \
    components/icons/hardware/svg/production/ic_router_24px.svg \
    components/icons/hardware/svg/production/ic_scanner_24px.svg \
    components/icons/hardware/svg/production/ic_security_24px.svg \
    components/icons/hardware/svg/production/ic_sim_card_24px.svg \
    components/icons/hardware/svg/production/ic_smartphone_24px.svg \
    components/icons/hardware/svg/production/ic_speaker_24px.svg \
    components/icons/hardware/svg/production/ic_speaker_group_24px.svg \
    components/icons/hardware/svg/production/ic_tablet_24px.svg \
    components/icons/hardware/svg/production/ic_tablet_android_24px.svg \
    components/icons/hardware/svg/production/ic_tablet_mac_24px.svg \
    components/icons/hardware/svg/production/ic_toys_24px.svg \
    components/icons/hardware/svg/production/ic_tv_24px.svg \
    components/icons/hardware/svg/production/ic_videogame_asset_24px.svg \
    components/icons/hardware/svg/production/ic_watch_24px.svg \
    components/icons/image/svg/production/ic_add_a_photo_24px.svg \
    components/icons/image/svg/production/ic_add_to_photos_24px.svg \
    components/icons/image/svg/production/ic_adjust_24px.svg \
    components/icons/image/svg/production/ic_assistant_24px.svg \
    components/icons/image/svg/production/ic_assistant_photo_24px.svg \
    components/icons/image/svg/production/ic_audiotrack_24px.svg \
    components/icons/image/svg/production/ic_blur_circular_24px.svg \
    components/icons/image/svg/production/ic_blur_linear_24px.svg \
    components/icons/image/svg/production/ic_blur_off_24px.svg \
    components/icons/image/svg/production/ic_blur_on_24px.svg \
    components/icons/image/svg/production/ic_brightness_1_24px.svg \
    components/icons/image/svg/production/ic_brightness_2_24px.svg \
    components/icons/image/svg/production/ic_brightness_3_24px.svg \
    components/icons/image/svg/production/ic_brightness_4_24px.svg \
    components/icons/image/svg/production/ic_brightness_5_24px.svg \
    components/icons/image/svg/production/ic_brightness_6_24px.svg \
    components/icons/image/svg/production/ic_brightness_7_24px.svg \
    components/icons/image/svg/production/ic_broken_image_24px.svg \
    components/icons/image/svg/production/ic_brush_24px.svg \
    components/icons/image/svg/production/ic_burst_mode_24px.svg \
    components/icons/image/svg/production/ic_camera_24px.svg \
    components/icons/image/svg/production/ic_camera_alt_24px.svg \
    components/icons/image/svg/production/ic_camera_front_24px.svg \
    components/icons/image/svg/production/ic_camera_rear_24px.svg \
    components/icons/image/svg/production/ic_camera_roll_24px.svg \
    components/icons/image/svg/production/ic_center_focus_strong_24px.svg \
    components/icons/image/svg/production/ic_center_focus_weak_24px.svg \
    components/icons/image/svg/production/ic_collections_24px.svg \
    components/icons/image/svg/production/ic_collections_bookmark_24px.svg \
    components/icons/image/svg/production/ic_color_lens_24px.svg \
    components/icons/image/svg/production/ic_colorize_24px.svg \
    components/icons/image/svg/production/ic_compare_24px.svg \
    components/icons/image/svg/production/ic_control_point_24px.svg \
    components/icons/image/svg/production/ic_control_point_duplicate_24px.svg \
    components/icons/image/svg/production/ic_crop_16_9_24px.svg \
    components/icons/image/svg/production/ic_crop_24px.svg \
    components/icons/image/svg/production/ic_crop_3_2_24px.svg \
    components/icons/image/svg/production/ic_crop_5_4_24px.svg \
    components/icons/image/svg/production/ic_crop_7_5_24px.svg \
    components/icons/image/svg/production/ic_crop_din_24px.svg \
    components/icons/image/svg/production/ic_crop_free_24px.svg \
    components/icons/image/svg/production/ic_crop_landscape_24px.svg \
    components/icons/image/svg/production/ic_crop_original_24px.svg \
    components/icons/image/svg/production/ic_crop_portrait_24px.svg \
    components/icons/image/svg/production/ic_crop_rotate_24px.svg \
    components/icons/image/svg/production/ic_crop_square_24px.svg \
    components/icons/image/svg/production/ic_dehaze_24px.svg \
    components/icons/image/svg/production/ic_details_24px.svg \
    components/icons/image/svg/production/ic_edit_24px.svg \
    components/icons/image/svg/production/ic_exposure_24px.svg \
    components/icons/image/svg/production/ic_exposure_neg_1_24px.svg \
    components/icons/image/svg/production/ic_exposure_neg_2_24px.svg \
    components/icons/image/svg/production/ic_exposure_plus_1_24px.svg \
    components/icons/image/svg/production/ic_exposure_plus_2_24px.svg \
    components/icons/image/svg/production/ic_exposure_zero_24px.svg \
    components/icons/image/svg/production/ic_filter_1_24px.svg \
    components/icons/image/svg/production/ic_filter_24px.svg \
    components/icons/image/svg/production/ic_filter_2_24px.svg \
    components/icons/image/svg/production/ic_filter_3_24px.svg \
    components/icons/image/svg/production/ic_filter_4_24px.svg \
    components/icons/image/svg/production/ic_filter_5_24px.svg \
    components/icons/image/svg/production/ic_filter_6_24px.svg \
    components/icons/image/svg/production/ic_filter_7_24px.svg \
    components/icons/image/svg/production/ic_filter_8_24px.svg \
    components/icons/image/svg/production/ic_filter_9_24px.svg \
    components/icons/image/svg/production/ic_filter_9_plus_24px.svg \
    components/icons/image/svg/production/ic_filter_b_and_w_24px.svg \
    components/icons/image/svg/production/ic_filter_center_focus_24px.svg \
    components/icons/image/svg/production/ic_filter_drama_24px.svg \
    components/icons/image/svg/production/ic_filter_frames_24px.svg \
    components/icons/image/svg/production/ic_filter_hdr_24px.svg \
    components/icons/image/svg/production/ic_filter_none_24px.svg \
    components/icons/image/svg/production/ic_filter_tilt_shift_24px.svg \
    components/icons/image/svg/production/ic_filter_vintage_24px.svg \
    components/icons/image/svg/production/ic_flare_24px.svg \
    components/icons/image/svg/production/ic_flash_auto_24px.svg \
    components/icons/image/svg/production/ic_flash_off_24px.svg \
    components/icons/image/svg/production/ic_flash_on_24px.svg \
    components/icons/image/svg/production/ic_flip_24px.svg \
    components/icons/image/svg/production/ic_gradient_24px.svg \
    components/icons/image/svg/production/ic_grain_24px.svg \
    components/icons/image/svg/production/ic_grid_off_24px.svg \
    components/icons/image/svg/production/ic_grid_on_24px.svg \
    components/icons/image/svg/production/ic_hdr_off_24px.svg \
    components/icons/image/svg/production/ic_hdr_on_24px.svg \
    components/icons/image/svg/production/ic_hdr_strong_24px.svg \
    components/icons/image/svg/production/ic_hdr_weak_24px.svg \
    components/icons/image/svg/production/ic_healing_24px.svg \
    components/icons/image/svg/production/ic_image_24px.svg \
    components/icons/image/svg/production/ic_image_aspect_ratio_24px.svg \
    components/icons/image/svg/production/ic_iso_24px.svg \
    components/icons/image/svg/production/ic_landscape_24px.svg \
    components/icons/image/svg/production/ic_leak_add_24px.svg \
    components/icons/image/svg/production/ic_leak_remove_24px.svg \
    components/icons/image/svg/production/ic_lens_24px.svg \
    components/icons/image/svg/production/ic_linked_camera_24px.svg \
    components/icons/image/svg/production/ic_looks_24px.svg \
    components/icons/image/svg/production/ic_looks_3_24px.svg \
    components/icons/image/svg/production/ic_looks_4_24px.svg \
    components/icons/image/svg/production/ic_looks_5_24px.svg \
    components/icons/image/svg/production/ic_looks_6_24px.svg \
    components/icons/image/svg/production/ic_looks_one_24px.svg \
    components/icons/image/svg/production/ic_looks_two_24px.svg \
    components/icons/image/svg/production/ic_loupe_24px.svg \
    components/icons/image/svg/production/ic_monochrome_photos_24px.svg \
    components/icons/image/svg/production/ic_movie_creation_24px.svg \
    components/icons/image/svg/production/ic_movie_filter_24px.svg \
    components/icons/image/svg/production/ic_music_note_24px.svg \
    components/icons/image/svg/production/ic_nature_24px.svg \
    components/icons/image/svg/production/ic_nature_people_24px.svg \
    components/icons/image/svg/production/ic_navigate_before_24px.svg \
    components/icons/image/svg/production/ic_navigate_next_24px.svg \
    components/icons/image/svg/production/ic_palette_24px.svg \
    components/icons/image/svg/production/ic_panorama_24px.svg \
    components/icons/image/svg/production/ic_panorama_fish_eye_24px.svg \
    components/icons/image/svg/production/ic_panorama_horizontal_24px.svg \
    components/icons/image/svg/production/ic_panorama_vertical_24px.svg \
    components/icons/image/svg/production/ic_panorama_wide_angle_24px.svg \
    components/icons/image/svg/production/ic_photo_24px.svg \
    components/icons/image/svg/production/ic_photo_album_24px.svg \
    components/icons/image/svg/production/ic_photo_camera_24px.svg \
    components/icons/image/svg/production/ic_photo_filter_24px.svg \
    components/icons/image/svg/production/ic_photo_library_24px.svg \
    components/icons/image/svg/production/ic_photo_size_select_actual_24px.svg \
    components/icons/image/svg/production/ic_photo_size_select_large_24px.svg \
    components/icons/image/svg/production/ic_photo_size_select_small_24px.svg \
    components/icons/image/svg/production/ic_picture_as_pdf_24px.svg \
    components/icons/image/svg/production/ic_portrait_24px.svg \
    components/icons/image/svg/production/ic_remove_red_eye_24px.svg \
    components/icons/image/svg/production/ic_rotate_90_degrees_ccw_24px.svg \
    components/icons/image/svg/production/ic_rotate_left_24px.svg \
    components/icons/image/svg/production/ic_rotate_right_24px.svg \
    components/icons/image/svg/production/ic_slideshow_24px.svg \
    components/icons/image/svg/production/ic_straighten_24px.svg \
    components/icons/image/svg/production/ic_style_24px.svg \
    components/icons/image/svg/production/ic_switch_camera_24px.svg \
    components/icons/image/svg/production/ic_switch_video_24px.svg \
    components/icons/image/svg/production/ic_tag_faces_24px.svg \
    components/icons/image/svg/production/ic_texture_24px.svg \
    components/icons/image/svg/production/ic_timelapse_24px.svg \
    components/icons/image/svg/production/ic_timer_10_24px.svg \
    components/icons/image/svg/production/ic_timer_24px.svg \
    components/icons/image/svg/production/ic_timer_3_24px.svg \
    components/icons/image/svg/production/ic_timer_off_24px.svg \
    components/icons/image/svg/production/ic_tonality_24px.svg \
    components/icons/image/svg/production/ic_transform_24px.svg \
    components/icons/image/svg/production/ic_tune_24px.svg \
    components/icons/image/svg/production/ic_view_comfy_24px.svg \
    components/icons/image/svg/production/ic_view_compact_24px.svg \
    components/icons/image/svg/production/ic_vignette_24px.svg \
    components/icons/image/svg/production/ic_wb_auto_24px.svg \
    components/icons/image/svg/production/ic_wb_cloudy_24px.svg \
    components/icons/image/svg/production/ic_wb_incandescent_24px.svg \
    components/icons/image/svg/production/ic_wb_iridescent_24px.svg \
    components/icons/image/svg/production/ic_wb_sunny_24px.svg \
    components/icons/maps/svg/production/ic_add_location_24px.svg \
    components/icons/maps/svg/production/ic_beenhere_24px.svg \
    components/icons/maps/svg/production/ic_directions_24px.svg \
    components/icons/maps/svg/production/ic_directions_bike_24px.svg \
    components/icons/maps/svg/production/ic_directions_boat_24px.svg \
    components/icons/maps/svg/production/ic_directions_bus_24px.svg \
    components/icons/maps/svg/production/ic_directions_car_24px.svg \
    components/icons/maps/svg/production/ic_directions_railway_24px.svg \
    components/icons/maps/svg/production/ic_directions_run_24px.svg \
    components/icons/maps/svg/production/ic_directions_subway_24px.svg \
    components/icons/maps/svg/production/ic_directions_transit_24px.svg \
    components/icons/maps/svg/production/ic_directions_walk_24px.svg \
    components/icons/maps/svg/production/ic_edit_location_24px.svg \
    components/icons/maps/svg/production/ic_ev_station_24px.svg \
    components/icons/maps/svg/production/ic_flight_24px.svg \
    components/icons/maps/svg/production/ic_hotel_24px.svg \
    components/icons/maps/svg/production/ic_layers_24px.svg \
    components/icons/maps/svg/production/ic_layers_clear_24px.svg \
    components/icons/maps/svg/production/ic_local_activity_24px.svg \
    components/icons/maps/svg/production/ic_local_airport_24px.svg \
    components/icons/maps/svg/production/ic_local_atm_24px.svg \
    components/icons/maps/svg/production/ic_local_bar_24px.svg \
    components/icons/maps/svg/production/ic_local_cafe_24px.svg \
    components/icons/maps/svg/production/ic_local_car_wash_24px.svg \
    components/icons/maps/svg/production/ic_local_convenience_store_24px.svg \
    components/icons/maps/svg/production/ic_local_dining_24px.svg \
    components/icons/maps/svg/production/ic_local_drink_24px.svg \
    components/icons/maps/svg/production/ic_local_florist_24px.svg \
    components/icons/maps/svg/production/ic_local_gas_station_24px.svg \
    components/icons/maps/svg/production/ic_local_grocery_store_24px.svg \
    components/icons/maps/svg/production/ic_local_hospital_24px.svg \
    components/icons/maps/svg/production/ic_local_hotel_24px.svg \
    components/icons/maps/svg/production/ic_local_laundry_service_24px.svg \
    components/icons/maps/svg/production/ic_local_library_24px.svg \
    components/icons/maps/svg/production/ic_local_mall_24px.svg \
    components/icons/maps/svg/production/ic_local_movies_24px.svg \
    components/icons/maps/svg/production/ic_local_offer_24px.svg \
    components/icons/maps/svg/production/ic_local_parking_24px.svg \
    components/icons/maps/svg/production/ic_local_pharmacy_24px.svg \
    components/icons/maps/svg/production/ic_local_phone_24px.svg \
    components/icons/maps/svg/production/ic_local_pizza_24px.svg \
    components/icons/maps/svg/production/ic_local_play_24px.svg \
    components/icons/maps/svg/production/ic_local_post_office_24px.svg \
    components/icons/maps/svg/production/ic_local_printshop_24px.svg \
    components/icons/maps/svg/production/ic_local_see_24px.svg \
    components/icons/maps/svg/production/ic_local_shipping_24px.svg \
    components/icons/maps/svg/production/ic_local_taxi_24px.svg \
    components/icons/maps/svg/production/ic_map_24px.svg \
    components/icons/maps/svg/production/ic_my_location_24px.svg \
    components/icons/maps/svg/production/ic_navigation_24px.svg \
    components/icons/maps/svg/production/ic_near_me_24px.svg \
    components/icons/maps/svg/production/ic_person_pin_24px.svg \
    components/icons/maps/svg/production/ic_person_pin_circle_24px.svg \
    components/icons/maps/svg/production/ic_pin_drop_24px.svg \
    components/icons/maps/svg/production/ic_place_24px.svg \
    components/icons/maps/svg/production/ic_rate_review_24px.svg \
    components/icons/maps/svg/production/ic_restaurant_24px.svg \
    components/icons/maps/svg/production/ic_restaurant_menu_24px.svg \
    components/icons/maps/svg/production/ic_satellite_24px.svg \
    components/icons/maps/svg/production/ic_store_mall_directory_24px.svg \
    components/icons/maps/svg/production/ic_streetview_24px.svg \
    components/icons/maps/svg/production/ic_subway_24px.svg \
    components/icons/maps/svg/production/ic_terrain_24px.svg \
    components/icons/maps/svg/production/ic_traffic_24px.svg \
    components/icons/maps/svg/production/ic_train_24px.svg \
    components/icons/maps/svg/production/ic_tram_24px.svg \
    components/icons/maps/svg/production/ic_transfer_within_a_station_24px.svg \
    components/icons/maps/svg/production/ic_zoom_out_map_24px.svg \
    components/icons/navigation/svg/production/ic_apps_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_back_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_downward_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_drop_down_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_drop_down_circle_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_drop_up_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_forward_24px.svg \
    components/icons/navigation/svg/production/ic_arrow_upward_24px.svg \
    components/icons/navigation/svg/production/ic_cancel_24px.svg \
    components/icons/navigation/svg/production/ic_check_24px.svg \
    components/icons/navigation/svg/production/ic_chevron_left_24px.svg \
    components/icons/navigation/svg/production/ic_chevron_right_24px.svg \
    components/icons/navigation/svg/production/ic_close_24px.svg \
    components/icons/navigation/svg/production/ic_expand_less_24px.svg \
    components/icons/navigation/svg/production/ic_expand_more_24px.svg \
    components/icons/navigation/svg/production/ic_first_page_24px.svg \
    components/icons/navigation/svg/production/ic_fullscreen_24px.svg \
    components/icons/navigation/svg/production/ic_fullscreen_exit_24px.svg \
    components/icons/navigation/svg/production/ic_last_page_24px.svg \
    components/icons/navigation/svg/production/ic_menu_24px.svg \
    components/icons/navigation/svg/production/ic_more_horiz_24px.svg \
    components/icons/navigation/svg/production/ic_more_vert_24px.svg \
    components/icons/navigation/svg/production/ic_refresh_24px.svg \
    components/icons/navigation/svg/production/ic_subdirectory_arrow_left_24px.svg \
    components/icons/navigation/svg/production/ic_subdirectory_arrow_right_24px.svg \
    components/icons/navigation/svg/production/ic_unfold_less_24px.svg \
    components/icons/navigation/svg/production/ic_unfold_more_24px.svg \
    components/icons/notification/svg/production/ic_adb_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_flat_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_flat_angled_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_individual_suite_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_legroom_extra_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_legroom_normal_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_legroom_reduced_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_recline_extra_24px.svg \
    components/icons/notification/svg/production/ic_airline_seat_recline_normal_24px.svg \
    components/icons/notification/svg/production/ic_bluetooth_audio_24px.svg \
    components/icons/notification/svg/production/ic_confirmation_number_24px.svg \
    components/icons/notification/svg/production/ic_disc_full_24px.svg \
    components/icons/notification/svg/production/ic_do_not_disturb_24px.svg \
    components/icons/notification/svg/production/ic_do_not_disturb_alt_24px.svg \
    components/icons/notification/svg/production/ic_do_not_disturb_off_24px.svg \
    components/icons/notification/svg/production/ic_do_not_disturb_on_24px.svg \
    components/icons/notification/svg/production/ic_drive_eta_24px.svg \
    components/icons/notification/svg/production/ic_enhanced_encryption_24px.svg \
    components/icons/notification/svg/production/ic_event_available_24px.svg \
    components/icons/notification/svg/production/ic_event_busy_24px.svg \
    components/icons/notification/svg/production/ic_event_note_24px.svg \
    components/icons/notification/svg/production/ic_folder_special_24px.svg \
    components/icons/notification/svg/production/ic_live_tv_24px.svg \
    components/icons/notification/svg/production/ic_mms_24px.svg \
    components/icons/notification/svg/production/ic_more_24px.svg \
    components/icons/notification/svg/production/ic_network_check_24px.svg \
    components/icons/notification/svg/production/ic_network_locked_24px.svg \
    components/icons/notification/svg/production/ic_no_encryption_24px.svg \
    components/icons/notification/svg/production/ic_ondemand_video_24px.svg \
    components/icons/notification/svg/production/ic_personal_video_24px.svg \
    components/icons/notification/svg/production/ic_phone_bluetooth_speaker_24px.svg \
    components/icons/notification/svg/production/ic_phone_forwarded_24px.svg \
    components/icons/notification/svg/production/ic_phone_in_talk_24px.svg \
    components/icons/notification/svg/production/ic_phone_locked_24px.svg \
    components/icons/notification/svg/production/ic_phone_missed_24px.svg \
    components/icons/notification/svg/production/ic_phone_paused_24px.svg \
    components/icons/notification/svg/production/ic_power_24px.svg \
    components/icons/notification/svg/production/ic_priority_high_24px.svg \
    components/icons/notification/svg/production/ic_rv_hookup_24px.svg \
    components/icons/notification/svg/production/ic_sd_card_24px.svg \
    components/icons/notification/svg/production/ic_sim_card_alert_24px.svg \
    components/icons/notification/svg/production/ic_sms_24px.svg \
    components/icons/notification/svg/production/ic_sms_failed_24px.svg \
    components/icons/notification/svg/production/ic_sync_24px.svg \
    components/icons/notification/svg/production/ic_sync_disabled_24px.svg \
    components/icons/notification/svg/production/ic_sync_problem_24px.svg \
    components/icons/notification/svg/production/ic_system_update_24px.svg \
    components/icons/notification/svg/production/ic_tap_and_play_24px.svg \
    components/icons/notification/svg/production/ic_time_to_leave_24px.svg \
    components/icons/notification/svg/production/ic_vibration_24px.svg \
    components/icons/notification/svg/production/ic_voice_chat_24px.svg \
    components/icons/notification/svg/production/ic_vpn_lock_24px.svg \
    components/icons/notification/svg/production/ic_wc_24px.svg \
    components/icons/notification/svg/production/ic_wifi_24px.svg \
    components/icons/places/svg/production/ic_ac_unit_24px.svg \
    components/icons/places/svg/production/ic_airport_shuttle_24px.svg \
    components/icons/places/svg/production/ic_all_inclusive_24px.svg \
    components/icons/places/svg/production/ic_beach_access_24px.svg \
    components/icons/places/svg/production/ic_business_center_24px.svg \
    components/icons/places/svg/production/ic_casino_24px.svg \
    components/icons/places/svg/production/ic_child_care_24px.svg \
    components/icons/places/svg/production/ic_child_friendly_24px.svg \
    components/icons/places/svg/production/ic_fitness_center_24px.svg \
    components/icons/places/svg/production/ic_free_breakfast_24px.svg \
    components/icons/places/svg/production/ic_golf_course_24px.svg \
    components/icons/places/svg/production/ic_hot_tub_24px.svg \
    components/icons/places/svg/production/ic_kitchen_24px.svg \
    components/icons/places/svg/production/ic_pool_24px.svg \
    components/icons/places/svg/production/ic_room_service_24px.svg \
    components/icons/places/svg/production/ic_rv_hookup_24px.svg \
    components/icons/places/svg/production/ic_smoke_free_24px.svg \
    components/icons/places/svg/production/ic_smoking_rooms_24px.svg \
    components/icons/places/svg/production/ic_spa_24px.svg \
    components/icons/social/svg/production/ic_cake_24px.svg \
    components/icons/social/svg/production/ic_domain_24px.svg \
    components/icons/social/svg/production/ic_group_24px.svg \
    components/icons/social/svg/production/ic_group_add_24px.svg \
    components/icons/social/svg/production/ic_location_city_24px.svg \
    components/icons/social/svg/production/ic_mood_24px.svg \
    components/icons/social/svg/production/ic_mood_bad_24px.svg \
    components/icons/social/svg/production/ic_notifications_24px.svg \
    components/icons/social/svg/production/ic_notifications_active_24px.svg \
    components/icons/social/svg/production/ic_notifications_none_24px.svg \
    components/icons/social/svg/production/ic_notifications_off_24px.svg \
    components/icons/social/svg/production/ic_notifications_paused_24px.svg \
    components/icons/social/svg/production/ic_pages_24px.svg \
    components/icons/social/svg/production/ic_party_mode_24px.svg \
    components/icons/social/svg/production/ic_people_24px.svg \
    components/icons/social/svg/production/ic_people_outline_24px.svg \
    components/icons/social/svg/production/ic_person_24px.svg \
    components/icons/social/svg/production/ic_person_add_24px.svg \
    components/icons/social/svg/production/ic_person_outline_24px.svg \
    components/icons/social/svg/production/ic_plus_one_24px.svg \
    components/icons/social/svg/production/ic_poll_24px.svg \
    components/icons/social/svg/production/ic_public_24px.svg \
    components/icons/social/svg/production/ic_school_24px.svg \
    components/icons/social/svg/production/ic_sentiment_dissatisfied_24px.svg \
    components/icons/social/svg/production/ic_sentiment_neutral_24px.svg \
    components/icons/social/svg/production/ic_sentiment_satisfied_24px.svg \
    components/icons/social/svg/production/ic_sentiment_very_dissatisfied_24px.svg \
    components/icons/social/svg/production/ic_sentiment_very_satisfied_24px.svg \
    components/icons/social/svg/production/ic_share_24px.svg \
    components/icons/social/svg/production/ic_whatshot_24px.svg \
    components/icons/toggle/svg/production/ic_check_box_24px.svg \
    components/icons/toggle/svg/production/ic_check_box_outline_blank_24px.svg \
    components/icons/toggle/svg/production/ic_indeterminate_check_box_24px.svg \
    components/icons/toggle/svg/production/ic_radio_button_checked_24px.svg \
    components/icons/toggle/svg/production/ic_radio_button_unchecked_24px.svg \
    components/icons/toggle/svg/production/ic_star_24px.svg \
    components/icons/toggle/svg/production/ic_star_border_24px.svg \
    components/icons/toggle/svg/production/ic_star_half_24px.svg \
    components/icons/LICENSE\
    fonts/Roboto/LICENSE.txt\
    /root/图片/spm6.png \
DISTFILES += \
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ClProtocol.def"\
    "C:/Program Files/JAI/SDK/library/CPP/include/CLProtocol/ClSerial.def"

FORMS += \
    mainwindow.ui
